### ISSUE TITLE
tabletojson.convertUrl is not a function

### ISSUE THREAD

**Issue by rrjanbiah** [rajatdhoot123/indian-courier-api#11]
Demo is throwing error:

https://indian-courier-api.herokuapp.com/ekart/FMPC0279658213

```json
{"error":{"message":"tabletojson.convertUrl is not a function"}}
```

**Comment by rajatdhoot123** [comment]
Endpoint updated kindly track here

https://indian-courier-api-premium.vercel.app/api/ekart/FMPC0279658213
